include: package:lint/analysis_options.yaml

linter:
  rules:
    implementation_imports: false

analyzer:
  exclude:
    # generated code
    - lib/*.reflectable.dart
    - test/*.reflectable.dart
    - lib/**/*.g.dart